fluidPage(titlePanel("DRE: GSEA Analysis against Complete MSigDB Signatures"),
          sidebarLayout(
            sidebarPanel(
              fileInput('cfile', 'Upload a two column (no header) tab-delimited .txt file containing gene symbol (column 1) and log/log2-Fold-Change of the genes from a post-differential expression analysis(column 2).',
                        accept=c('text/txt', 'text/txt')),
              downloadButton("downloadData", label = "Download an Example Input Data"),
              hr(),
              selectInput(inputId = 'corganism', label = 'Select an organism',
                          choices = organism, multiple =F, selected = "Homo_sapiens"),
              selectInput(inputId = 'cclasses', label = 'Select a category',
                          choices = cclasses, multiple =F, selected = "C2"),
              h5("Example:"),
              h6("GZMB 6.446"),
              h6("TRPV6 5.278"),
              h6(".."),
              h6("SELENOP  -2.804"),
              actionButton("run", "Start Analysis"),
              hr(),
              h5("Pathway Category:"),tags$a(href="https://www.gsea-msigdb.org/gsea/msigdb/human/collections.jsp#H", "H (hallmark gene sets)", target="_blank"),
              br(),
              tags$a(href="https://www.gsea-msigdb.org/gsea/msigdb/human/collections.jsp#C1", "C1 (positional gene sets)", target="_blank"),
              br(),
              tags$a(href="https://www.gsea-msigdb.org/gsea/msigdb/human/collections.jsp#C2", "C2 (curated gene sets)", target="_blank"),
              br(),
              tags$a(href="https://www.gsea-msigdb.org/gsea/msigdb/human/collections.jsp#C3", "C3 (regulatory target gene sets)", target="_blank"),
              br(),
              tags$a(href="https://www.gsea-msigdb.org/gsea/msigdb/human/collections.jsp#C4", "C4 (computational gene sets)", target="_blank"),
              br(),
              tags$a(href="https://www.gsea-msigdb.org/gsea/msigdb/human/collections.jsp#C5", "C5 (ontology gene sets)", target="_blank"),
              br(),
              tags$a(href="https://www.gsea-msigdb.org/gsea/msigdb/human/collections.jsp#C6", "C6 (oncogenic signature gene sets)", target="_blank"),
              br(),
              tags$a(href="https://www.gsea-msigdb.org/gsea/msigdb/human/collections.jsp#C7", "C7 (immunologic signature gene sets)", target="_blank"),
              br(),
              tags$a(href="https://www.gsea-msigdb.org/gsea/msigdb/human/collections.jsp#C8", "C8 (cell type signature gene sets)", target="_blank"),
            ),
            mainPanel(
              fluidRow(column(12,selectInput(inputId = 'cgsea', label = 'Select or type to search for a pathway to view (press backspace to delete current selection)',width="100%",
                                             choices = "", multiple = F, selected = "", selectize = T))),
              tabsetPanel(
                tabPanel("Plot",
                         br(),
                         fluidRow(column(12,withSpinner(plotlyOutput('plot', width = "100%", height = 500))))
                ),
                tabPanel("Table",br(),
                         # hr(),
                         fluidRow(column(12, DTOutput('table')))),
                tabPanel("Example",br(),
                         div(withSpinner(imageOutput("example", width = "100%", height = "100%")), align = "center"))
                
              ))),
)
