fluidPage(titlePanel("DRE: Drug-Pathway Database"),
          sidebarLayout(
            sidebarPanel(
           selectizeInput("organism","Type to search for an organism*", choices = organism, selected = NULL, options = list(placeholder = 'Please search and click to select an option', onInitialize = I('function() { this.setValue(""); }'))),
            # selectInput("type","Select a data type", choices = c("Drug","Pathway"), selected = "Drug"),
           selectizeInput("type","Select a data type", choices = c("Pathway","Drug"), selected = NULL, options = list(placeholder = 'Please click to select an option', onInitialize = I('function() { this.setValue(""); }'))),
            conditionalPanel(condition = "input.type == 'Drug'",
                           selectizeInput("drugname","Type to search for a drug name*", choices = drugname, selected = NULL, options = list(placeholder = 'Please search and click to select an option', onInitialize = I('function() { this.setValue(""); }'))),
                           selectizeInput("pathwayclass1","Type to search for a pathway category*", choices = pathwayclass, selected = NULL, options = list(placeholder = 'Please search and click to select an option', onInitialize = I('function() { this.setValue(""); }'))),
                           selectizeInput("pathway","Type to search for a pathway to view its GSEA plot*", choices = NULL, selected = NULL, options = list(placeholder = 'Please search and click to select an option', onInitialize = I('function() { this.setValue(""); }')))),
            conditionalPanel(condition = "input.type == 'Pathway'",
           selectizeInput("pathwayclass2","Type to search for a pathway category*", choices = pathwayclass, selected = NULL, options = list(placeholder = 'Please search and click to select an option', onInitialize = I('function() { this.setValue(""); }'))),
           selectizeInput("pathway2","Type to search for a pathway*", choices = NULL, selected = NULL, options = list(placeholder = 'Please search and click to select an option', onInitialize = I('function() { this.setValue(""); }')))),
           tags$i("*Press backspace to delete current search"),
           hr(),
                             h5("Pathway Category:"),tags$a(href="https://www.gsea-msigdb.org/gsea/msigdb/human/collections.jsp#H", "H (hallmark gene sets)", target="_blank"),
                             br(),
                             tags$a(href="https://www.gsea-msigdb.org/gsea/msigdb/human/collections.jsp#C1", "C1 (positional gene sets)", target="_blank"),
                             br(),
                             tags$a(href="https://www.gsea-msigdb.org/gsea/msigdb/human/collections.jsp#C2", "C2 (curated gene sets)", target="_blank"),
                             br(),
                             tags$a(href="https://www.gsea-msigdb.org/gsea/msigdb/human/collections.jsp#C3", "C3 (regulatory target gene sets)", target="_blank"),
                             br(),
                             tags$a(href="https://www.gsea-msigdb.org/gsea/msigdb/human/collections.jsp#C4", "C4 (computational gene sets)", target="_blank"),
                             br(),
                             tags$a(href="https://www.gsea-msigdb.org/gsea/msigdb/human/collections.jsp#C5", "C5 (ontology gene sets)", target="_blank"),
                             br(),
                             tags$a(href="https://www.gsea-msigdb.org/gsea/msigdb/human/collections.jsp#C6", "C6 (oncogenic signature gene sets)", target="_blank"),
                             br(),
                             tags$a(href="https://www.gsea-msigdb.org/gsea/msigdb/human/collections.jsp#C7", "C7 (immunologic signature gene sets)", target="_blank"),
                             br(),
                             tags$a(href="https://www.gsea-msigdb.org/gsea/msigdb/human/collections.jsp#C8", "C8 (cell type signature gene sets)", target="_blank"),
            # selectInput("pathway","Select a pathway", choices = pathway, selected = pathway[1])
            ),
            mainPanel(
              tabsetPanel(id = "tabs",
                tabPanel("Top Drug-Pathway Associations",
                         br(),
                         useShinyjs(),
                         withSpinner(downloadablePlotlyUI('plot1', height = "700px")),
                         # hr(),
                         # fluidRow(
                         #   conditionalPanel(condition = "input.type == 'Pathway'",
                         #                    withSpinner(downloadablePlotlyUI('plot2',height = "500px")))
                         # )
                         ),
                # downloadablePlotlyUI("plot", height = 600, width = "100%", inline = T)%>% withSpinner()),
                tabPanel("Query Table",br(),
                         conditionalPanel(condition = "input.type == 'Drug'",
                                          h5("Drug Information:"),
                                          uiOutput("drugdesc")),
                         br(),
                         conditionalPanel(condition = "input.type == 'Drug'",dataTableOutput("drugtable", width = "100%", height = 400)%>% withSpinner()),
                         conditionalPanel(condition = "input.type == 'Pathway'",dataTableOutput("pathwaytable", width = "100%", height = 400)%>% withSpinner())),
                
                                 tabPanel("GSEA Plot",br(),
                                 withSpinner(downloadablePlotlyUI('plot2', height = "700px")),
                                 fluidRow(column(12, DTOutput('gseatable')))),
                tabPanel("Example",br(),
                         div(withSpinner(imageOutput("example", width = "100%", height = "100%")), align = "center")),
           ))
          ),
)
